server:
  port: 8085
spring:
  application:
    name: s-gemena

  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: s-gemena
      authentication-database: admin
      port: 27017